var width = 10;
var height = 5;
var area = width * height;
console.log("Area:", area);
console.log("Type of Area:", typeof area);
var bill = 50;
var payment = 75;
var change = payment - bill;
console.log("Change:", change);
console.log("Type of Change:", typeof change);
var quizzes = 80;
var midterm = 75;
var final = 90;
var grade = (quizzes + midterm + final) / 3;
console.log("Grade:", grade);
console.log("Type of Grade:", typeof grade);
var firstName = 'Tom';
var lastName = 'Jerry';
var fullName = firstName + " " + lastName;
console.log("Full Name:", fullName);
console.log("Type of Full Name:", typeof fullName);
var pH = 6;
var isAcidic = pH < 7;
console.log("Is Acidic:", isAcidic);
console.log("Type of Is Acidic:", typeof isAcidic);
var headCount = 300;
var isSparta = headCount === 300;
console.log("Is Sparta:", isSparta);
console.log("Type of Is Sparta:", typeof isSparta);
var motto = fullName;
motto += ' is the GOAT';
console.log("Motto:", motto);
console.log("Type of Motto:", typeof motto);
